### ISSUE TITLE
version of unity

### ISSUE THREAD

**Issue by chingiz** [ADA-SITE-CSCI4836-2018-Fall/week-1-demo#2]
The version of Unity that you are using is 2017. While importing project to 2018 version multiple problems occur.

**Comment by ayusubov** [comment]
Thanks for raising it @Chingiz ! Let me install the newest version of Unity and see how does it work.

**Comment by ayusubov** [comment]
C'mon, gentlemen, not a bog deal. Unity 2018 opens it alright and it works seamlessly. Just opened and saved in Unity 2018 to stop @Chingiz 's grumble :-)
